### ISSUE TITLE
add Rock the JVM?

### ISSUE THREAD

**Issue by SethTisue** [softinio/scalanews#12]
@daniel-ciocirlan do you have an RSS feed that could be aggregated here?

I was looking at https://github.com/softinio/scalanews/blob/main/docs/Resources/Blog_Directory.md and trying to think of obvious things that were missing and Rock the JVM was one of the first things that came to mind

**Comment by daniel-ciocirlan** [comment]
Yes! [Rock the JVM blog RSS](https://blog.rockthejvm.com/feed.xml)

**Comment by softinio** [comment]
Thanks both. On it. Will be included in my next PR which is imminent.

**Comment by softinio** [comment]
resolved by #16
