### ISSUE TITLE
Front page lacks date

### ISSUE THREAD

**Issue by SethTisue** [softinio/scalanews#15]
It isn't clear if I'm looking at news from today, last week, last month...

or 5 years ago — well, I guess I can see it says "2023" on the conference dates

**Comment by softinio** [comment]
@SethTisue My original thought was what you see in the homepage won't need a date as that is what is current and latest edition.  

When a new edition comes out, the previous edition moves to the sidebar with an archive date added.

What do you think is that good or shall I add a date to the current edition too?

Thanks.

**Comment by softinio** [comment]
@SethTisue now that I published the new edition, take a look to see what I mean (archive section):
https://www.scalanews.net/

**Comment by SethTisue** [comment]
that certainly helps, but I would still suggest showing the current date as well. it's still useful to know whether what I'm looking it is 0 days old or 6 days old. also the dates off to the side are there if I really look, but are easy to miss.

nearly ever blog and blog platform shows the date on the top post; Scala Times shows the date prominently; This Week in Scala shows the date prominently; it's what people expect

**Comment by softinio** [comment]
@SethTisue thanks for feedback. Will make that change.
